baseURL: https://ilanderreche-personalwebpage.netlify.app/
languageCode: en-us
title: Forty
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    #buttonText: Get Started
    subtitle: |-
      This is my first webpage created with R. You'll find here some of my contact details,a map of all the countries I have visited and a project I did while studying the MiF 
      at LBS.
    title: Hi, my name is Ignacio Landerreche
  blog: {}
  contact:
    address:
      - city: London. UK
        country: GB
        street: London Business School. Regent's Park. London. NW1 4SA ; Taunton Centre. 25 Taunton Place
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: landerreche@hotmail.com
        title: Email
    enable: yes
    phone:
      - phone: LBS Phone:+44 (0)20 7000 7001
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Landerreche
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
   #   - icon: fa-twitter
  #      label: Twitter
   #     url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/ignacio.landerreche/
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/landerreche/
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/ignaciolanderreche
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/ignaciolanderrechev/
  image: ''
  name: Ignacio Landerreche
  navigation:
   # button1:
    #  - name: Get Started
     #   url: blogs
    #button2:
     # - name: Log In
      #  url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
   #   - name: Generic Blog
    #    url: blogs/ipsum
     # - name: Elements
      #  url: elements.html
    menu: Menu
    subtitle: First webpage
    title: Landerreche
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Aliquam
        url: blogs/aliquam
      - image: pic02.jpg
        subtitle: Feugiat Amet Tempus
        title: Tempus
        url: blogs/tempus
     # - image: pic03.jpg
      #  subtitle: Lorem Etiam Nullam
       # title: Magna
        #url: blogs/magna
      #- image: pic04.jpg
       # subtitle: Nisl Sed Aliquam
        #title: Ipsum
        #url: blogs/ipsum
      #- image: pic05.jpg
       # subtitle: Ipsum Dolor Sit Amet
        #title: Consequat
        #url: blogs/ipsum
      #- image: pic06.jpg
       # subtitle: Feugiat Amet Tempus
        #title: Etiam
        #url: blogs/ipsum
 # two:
    #buttonText: Get Started
    #enable: yes
    #subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
     # \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
      #condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      #pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
      #Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
      #amet pharetra et feugiat tempus."
    #title: Massa libero
    #url: blogs
